# Generated by Django 6.1.1 on 2026-09-30 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField(verbose_name='Número de día (ej: 1, 2, 3)')),
                ('fecha', models.DateField()),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen del día')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nombre de la actividad')),
                ('hora', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='viajes.diaviaje')),
            ],
        ),
    ]
