# Generated by Django 6.1.1 on 2026-09-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_diaviaje_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaviaje',
            name='resumen',
        ),
        migrations.AddField(
            model_name='diaviaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diaviaje',
            name='numero_dia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='viajes/fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='viajes.diaviaje')),
            ],
        ),
    ]
