# Generated by Django 6.1.1 on 2026-10-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_remove_diaviaje_resumen_diaviaje_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='lugar',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='titulo',
        ),
        migrations.AddField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField()),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion_gps', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='dias/')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='viajes.viaje')),
            ],
        ),
        migrations.AlterField(
            model_name='actividad',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='viajes.dia'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='viajes.dia'),
        ),
        migrations.DeleteModel(
            name='DiaViaje',
        ),
    ]
