# Generated by Django 6.1.1 on 2026-10-02 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_chilean_peso_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='costo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='presupuesto',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
