# Generated by Django 6.1.1 on 2026-10-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_alter_actividad_costo_alter_gasto_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='viajes.dia'),
        ),
    ]
