# Generated by Django 6.1.1 on 2026-10-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0008_gasto_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
