# Generated by Django 6.1.1 on 2026-10-04 22:25

import django.db.models.deletion
from django.db import migrations, models


def populate_activity_trip_and_date(apps, schema_editor):
    Actividad = apps.get_model("viajes", "Actividad")
    database = schema_editor.connection.alias
    for actividad in Actividad.objects.using(database).select_related("dia").iterator():
        if actividad.dia_id:
            actividad.viaje_id = actividad.dia.viaje_id
            actividad.fecha = actividad.dia.fecha
            actividad.save(update_fields=["viaje", "fecha"])


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_alter_actividad_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='viajes.viaje'),
        ),
        migrations.RunPython(
            populate_activity_trip_and_date,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='viajes.dia'),
        ),
    ]
